title: Render
tagline: Swift and UIKit a la React.

# The GitHub repo for your project
ghrepo: "alexdrone/Render"

# Use these color settings to determine your colour scheme for the site.
color:
  # primary should be a vivid color that reflects the project's brand
  primary: "#97dccf"
  # secondary should be a subtle light or dark color used on page backgrounds
  secondary: "#ffffff"
  # Use the following to specify whether the previous two colours are 'light'
  # or 'dark' and therefore what colors can be overlaid on them
  primary-overlay: "light"
  secondary-overlay: "light"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: :compressed

redcarpet:
  extensions: [with_toc_data]
#theme: jekyll-theme-minimal