name: Render
options:
  deploymentTarget:
    iOS: 10.0
  usesTabs: false
  indentWidth: 2
targets:
  RenderNeutrino: &base
    platform: iOS
    type: framework
    sources: 
      - render/
    headers: 
      - render/RenderNeutrino.h
      - render/deps/yoga/
      - render/mods/deps/yaml/yaml.h
    settings:
      base:
        INFOPLIST_FILE: render/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.alexdrone.render
        PLATFORM: platform $platform
        SWIFT_WHOLE_MODULE_OPTIMIZATION: YES
        RENDER_MOD_INSPECTOR: YES
        RENDER_MOD_STYLESHEET: YES
        OTHERCFLAGS: -DRENDER_MOD_INSPECTOR -DRENDER_MOD_STYLESHEET
      configFiles:
        Debug: configs/Debug.xcconfig
        Release: configs/Release.xcconfig
  Test:
    platform: iOS
    type: bundle.unit-test
    sources:
      - test
    dependencies:
      - target: RenderNeutrino
    scheme:
      testTargets:
        - Test
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YES
          isEnabled: true
