name: Render
options:
  deploymentTarget:
    iOS: 10.0
  usesTabs: false
  indentWidth: 2
targets:
  RenderNeutrino: &base
    platform: iOS
    type: framework
    sources:
      - render/
    headers:
      - render/RenderNeutrino.h
      - render/deps/yoga/
      - render/mods/deps/yaml/yaml.h
    settings:
      base:
        INFOPLIST_FILE: render/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.render.neutrino
        PLATFORM: platform $platform
        GCC_GENERATE_DEBUGGING_SYMBOLS: YES
        GCC_DEBUGGING_SYMBOLS: full,
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ONLY_ACTIVE_ARCH: NO
        VALID_ARCHS: arm64 armv7 armv7s i386 x86_64
        SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
      configFiles:
        Debug: configs/Debug.xcconfig
        Release: configs/Release.xcconfig
    postbuildScripts:
      - name: Dist
      - script: PRODUCT="${BUILT_PRODUCTS_DIR}/${TARGET_NAME}"; cp -R "${PRODUCT}.framework" ./bin; cp -R "${PRODUCT}.framework.dSYM" ./bin; cd ./bin; zip -r dist.zip RenderNeutrino.framework.dSYM RenderNeutrino.framework;
  Test:
    platform: iOS
    type: bundle.unit-test
    sources:
      - test
    dependencies:
      - target: RenderNeutrino
    scheme:
      testTargets:
        - Test
      gatherCoverageData: true
      environmentVariables:
        - variable: TEST
          value: YES
          isEnabled: true
