name: RenderInspector
options:
  deploymentTarget:
    iOS: 10.0
  usesTabs: false
  indentWidth: 2
targets:
  RenderInspector: &base
    platform: iOS
    type: framework
    sources:
      - inspector/
    headers:
      - inspector/RenderInspector.h
    settings:
      base:
        INFOPLIST_FILE: inspector/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.render.inspector
        PLATFORM: platform $platform
        SWIFT_WHOLE_MODULE_OPTIMIZATION: YES
        GCC_GENERATE_DEBUGGING_SYMBOLS: YES
        GCC_DEBUGGING_SYMBOLS: full,
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ONLY_ACTIVE_ARCH: NO
        SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
        SWIFT_VERSION: 4.2
      configFiles:
        Debug: configs/Debug.xcconfig
        Release: configs/Release.xcconfig
    postbuildScripts:
      - name: Dist
      - script: PRODUCT="${BUILT_PRODUCTS_DIR}/${TARGET_NAME}"; cp -R "${PRODUCT}.framework" ../../../bin/; cp -R "${PRODUCT}.framework.dSYM" ../../../bin/;
