name: RenderGenerator
targets:
  Generate:
    platform: macOS
    type: application
    sources: 
      - .
      - ../../../render/mods/stylesheet/
    headers: 
      - ../../../render/mods/stylesheet/deps/yaml.h
      - ./generate-Bridging-Header.h
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: ./generate-Bridging-Header.h
    scheme:
      gatherCoverageData: true
      environmentVariables:
        - variable: RENDER_MOD_STYLESHEET
          value: YES
          isEnabled: true