name: RenderGenerator
targets:
  Generate:
    platform: macOS
    type: application
    sources:
      - .
      - ../../../render/mods/stylesheet/deps/yaml.h
      - ../../../render/mods/stylesheet/deps/yaml.c
      - ../../../render/mods/stylesheet/deps/YamlBridge.swift
    headers:
      - ../../../render/mods/stylesheet/deps/yaml.h
      - ./generate-Bridging-Header.h
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: ./generate-Bridging-Header.h
    postbuildScripts:
      - name: Dist
      - script: PRODUCT="${BUILT_PRODUCTS_DIR}/${TARGET_NAME}"; cp -R "${PRODUCT}.app/Contents/MacOS/Generate" ../../render-generate; cd ../../; chmod +x render-generate;
    scheme:
      gatherCoverageData: true
      environmentVariables:
        - variable: RENDER_MOD_STYLESHEET
          value: YES
          isEnabled: true
